// Copyright (c) Open Tournament Project, All Rights Reserved.

/////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "NativeGameplayTags.h"

/////////////////////////////////////////////////////////////////////////////////////////////////

namespace URGameplayTags
{
    OPENTOURNAMENT_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MatchState_InProgress_Countdown);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MatchState_InProgress_Match);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MatchState_InProgress_Overtime);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MatchState_InProgress_Warmup);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Movement_Jumping);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Movement_Dodging);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Movement_Crouching);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Movement_Running);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Physics_Walking);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Physics_Falling);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Physics_Swimming);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_States_Physics_Flying);

    //

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

    //

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);

    //

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

    //

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

    //

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crosshair_Enable);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crosshair_Disable);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crosshair_HitRegister);

    //

    // These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
    OPENTOURNAMENT_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
    OPENTOURNAMENT_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

    OPENTOURNAMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
};
